// ZONA DE PRUEBAS HTTP

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "angelolma2080@gmail.com",
  "password": "nuvaContra1234"
}

### Endpoint Protegido
GET http://localhost:8080/auth/protectedTest
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmdlbG9sbWEyMDgwQGdtYWlsLmNvbSIsImlhdCI6MTc2MTM1NjMxNSwiZXhwIjoxNzYxMzU5OTE1fQ.yfTd_DKKysSIaTpus73m0f8eMVg_EqSWYsAuKV2jA4M

### Registro
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "pepe@pepe.com",
  "password": "prueba123"
}

### Logout
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmdlbG9sbWEyMDgwQGdtYWlsLmNvbSIsImlhdCI6MTc2MTI3NDc0NCwiZXhwIjoxNzYxMjc4MzQ0fQ.bUKRPPyDQspEXiZBD09yiJuPpNJ952uCYptz1PHXh10

### Recuperar contraseña - envia token
POST http://localhost:8080/auth/recuperar
Content-Type: application/json

{
  "email": "angelolma2080@gmail.com"
}

### Cambiar contraseña con token
POST http://localhost:8080/auth/cambiar-password
Content-Type: application/json

{
  "email": "angelolma2080@gmail.com",
  "token": "151e456d-336e-42df-acae-4f38ec7a3f57",
  "nuevaPassword": "contraseña123"
}

### Obtener todos los productos
GET http://localhost:8080/products/getAllProducts
